#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Erpbilansocial")]
public partial class DataLayerExperienceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  partial void InsertUsersession(Usersession instance);
  partial void UpdateUsersession(Usersession instance);
  partial void DeleteUsersession(Usersession instance);
    #endregion
    public DataLayerExperienceDataContext() :
base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ErpbilansocialConnectionString"].ConnectionString, mappingSource)
    {
        OnCreated();
    }

    public DataLayerExperienceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataLayerExperienceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Usersession> Usersession
	{
		get
		{
			return this.GetTable<Usersession>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countSexe")]
	public ISingleResult<countSexeResult> countSexe()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countSexeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countFonction")]
	public ISingleResult<countFonctionResult> countFonction()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countFonctionResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countDateEmbauche")]
	public ISingleResult<countDateEmbaucheResult> countDateEmbauche()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countDateEmbaucheResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countDateDepart")]
	public ISingleResult<countDateDepartResult> countDateDepart()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countDateDepartResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countDepartement")]
	public ISingleResult<countDepartementResult> countDepartement()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countDepartementResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountSalaire")]
	public ISingleResult<CountSalaireResult> CountSalaire()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<CountSalaireResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.countEffTotal")]
	public ISingleResult<countEffTotalResult> countEffTotal()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<countEffTotalResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRepartitionParAge")]
	public ISingleResult<GetRepartitionParAgeResult> GetRepartitionParAge()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetRepartitionParAgeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRepartitionParTypeContrat")]
	public ISingleResult<GetRepartitionParTypeContratResult> GetRepartitionParTypeContrat()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetRepartitionParTypeContratResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTauxTurnover")]
	public ISingleResult<GetTauxTurnoverResult> GetTauxTurnover()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetTauxTurnoverResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRepartitionHandicap")]
	public ISingleResult<GetRepartitionHandicapResult> GetRepartitionHandicap()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<GetRepartitionHandicapResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateUsersession")]
	public int updateUsersession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="NVarChar(MAX)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(MAX)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Prenom", DbType="NVarChar(MAX)")] string nom_Prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Role", DbType="NVarChar(MAX)")] string iD_Role)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, login, password, email, nom_Prenom, iD_Role);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateUsersession1")]
	public int updateUsersession1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(100)")] string password)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, password);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Permition_GetByIDRole")]
	public ISingleResult<Permition_GetByIDRoleResult> Permition_GetByIDRole([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Role", DbType="Int")] System.Nullable<int> iD_Role)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD_Role);
		return ((ISingleResult<Permition_GetByIDRoleResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountAgeMoy")]
	public ISingleResult<CountAgeMoyResult> CountAgeMoy()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<CountAgeMoyResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CountAnciennte")]
	public ISingleResult<CountAnciennteResult> CountAnciennte()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<CountAnciennteResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Afficher_Salaire_Min")]
	public ISingleResult<Afficher_Salaire_MinResult> Afficher_Salaire_Min()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<Afficher_Salaire_MinResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Afficher_Salaire_Max")]
	public ISingleResult<Afficher_Salaire_MaxResult> Afficher_Salaire_Max()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<Afficher_Salaire_MaxResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertUsersession")]
	public int insertUsersession([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Prenom", DbType="NVarChar(MAX)")] string nom_Prenom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Login", DbType="NVarChar(MAX)")] string login, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(MAX)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(MAX)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Role", DbType="Int")] System.Nullable<int> iD_Role)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Prenom, login, email, password, iD_Role);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Afficher_Abs_Max")]
	public ISingleResult<Afficher_Abs_MaxResult> Afficher_Abs_Max()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<Afficher_Abs_MaxResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Afficher_Abs_Moyen")]
	public ISingleResult<Afficher_Abs_MoyenResult> Afficher_Abs_Moyen()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<Afficher_Abs_MoyenResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usersession")]
public partial class Usersession : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Login;
	
	private string _Password;
	
	private string _Email;
	
	private string _Nom_Prenom;
	
	private System.Nullable<int> _ID_Role;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNom_PrenomChanging(string value);
    partial void OnNom_PrenomChanged();
    partial void OnID_RoleChanging(System.Nullable<int> value);
    partial void OnID_RoleChanged();
    #endregion
	
	public Usersession()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NChar(10)")]
	public string Login
	{
		get
		{
			return this._Login;
		}
		set
		{
			if ((this._Login != value))
			{
				this.OnLoginChanging(value);
				this.SendPropertyChanging();
				this._Login = value;
				this.SendPropertyChanged("Login");
				this.OnLoginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(MAX)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Prenom", DbType="NVarChar(MAX)")]
	public string Nom_Prenom
	{
		get
		{
			return this._Nom_Prenom;
		}
		set
		{
			if ((this._Nom_Prenom != value))
			{
				this.OnNom_PrenomChanging(value);
				this.SendPropertyChanging();
				this._Nom_Prenom = value;
				this.SendPropertyChanged("Nom_Prenom");
				this.OnNom_PrenomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Role", DbType="Int")]
	public System.Nullable<int> ID_Role
	{
		get
		{
			return this._ID_Role;
		}
		set
		{
			if ((this._ID_Role != value))
			{
				this.OnID_RoleChanging(value);
				this.SendPropertyChanging();
				this._ID_Role = value;
				this.SendPropertyChanged("ID_Role");
				this.OnID_RoleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class countSexeResult
{
	
	private System.Nullable<int> _Nbr_Sexe;
	
	private string _Description;
	
	public countSexeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nbr_Sexe", DbType="Int")]
	public System.Nullable<int> Nbr_Sexe
	{
		get
		{
			return this._Nbr_Sexe;
		}
		set
		{
			if ((this._Nbr_Sexe != value))
			{
				this._Nbr_Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}

public partial class countFonctionResult
{
	
	private System.Nullable<int> _Nbr_Fonction;
	
	private string _Description;
	
	public countFonctionResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nbr_Fonction", DbType="Int")]
	public System.Nullable<int> Nbr_Fonction
	{
		get
		{
			return this._Nbr_Fonction;
		}
		set
		{
			if ((this._Nbr_Fonction != value))
			{
				this._Nbr_Fonction = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}

public partial class countDateEmbaucheResult
{
	
	private System.Nullable<int> _Number;
	
	private System.Nullable<int> _Année;
	
	public countDateEmbaucheResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int")]
	public System.Nullable<int> Number
	{
		get
		{
			return this._Number;
		}
		set
		{
			if ((this._Number != value))
			{
				this._Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Année", DbType="Int")]
	public System.Nullable<int> Année
	{
		get
		{
			return this._Année;
		}
		set
		{
			if ((this._Année != value))
			{
				this._Année = value;
			}
		}
	}
}

public partial class countDateDepartResult
{
	
	private System.Nullable<int> _Number;
	
	private System.Nullable<int> _Année;
	
	public countDateDepartResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int")]
	public System.Nullable<int> Number
	{
		get
		{
			return this._Number;
		}
		set
		{
			if ((this._Number != value))
			{
				this._Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Année", DbType="Int")]
	public System.Nullable<int> Année
	{
		get
		{
			return this._Année;
		}
		set
		{
			if ((this._Année != value))
			{
				this._Année = value;
			}
		}
	}
}

public partial class countDepartementResult
{
	
	private System.Nullable<int> _Nbr_Departement;
	
	private string _Description;
	
	public countDepartementResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nbr_Departement", DbType="Int")]
	public System.Nullable<int> Nbr_Departement
	{
		get
		{
			return this._Nbr_Departement;
		}
		set
		{
			if ((this._Nbr_Departement != value))
			{
				this._Nbr_Departement = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}

public partial class CountSalaireResult
{
	
	private System.Nullable<int> _Number;
	
	private System.Nullable<int> _ID_Employes;
	
	private System.Nullable<double> _salaire;
	
	private System.Nullable<int> _Annee;
	
	private string _Description;
	
	public CountSalaireResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Number", DbType="Int")]
	public System.Nullable<int> Number
	{
		get
		{
			return this._Number;
		}
		set
		{
			if ((this._Number != value))
			{
				this._Number = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Employes", DbType="Int")]
	public System.Nullable<int> ID_Employes
	{
		get
		{
			return this._ID_Employes;
		}
		set
		{
			if ((this._ID_Employes != value))
			{
				this._ID_Employes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaire", DbType="Float")]
	public System.Nullable<double> salaire
	{
		get
		{
			return this._salaire;
		}
		set
		{
			if ((this._salaire != value))
			{
				this._salaire = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annee", DbType="Int")]
	public System.Nullable<int> Annee
	{
		get
		{
			return this._Annee;
		}
		set
		{
			if ((this._Annee != value))
			{
				this._Annee = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
}

public partial class countEffTotalResult
{
	
	private System.Nullable<int> _EffectifTotal;
	
	public countEffTotalResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectifTotal", DbType="Int")]
	public System.Nullable<int> EffectifTotal
	{
		get
		{
			return this._EffectifTotal;
		}
		set
		{
			if ((this._EffectifTotal != value))
			{
				this._EffectifTotal = value;
			}
		}
	}
}

public partial class GetRepartitionParAgeResult
{
	
	private string _TrancheAge;
	
	private System.Nullable<int> _NombreEmployes;
	
	public GetRepartitionParAgeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrancheAge", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string TrancheAge
	{
		get
		{
			return this._TrancheAge;
		}
		set
		{
			if ((this._TrancheAge != value))
			{
				this._TrancheAge = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmployes", DbType="Int")]
	public System.Nullable<int> NombreEmployes
	{
		get
		{
			return this._NombreEmployes;
		}
		set
		{
			if ((this._NombreEmployes != value))
			{
				this._NombreEmployes = value;
			}
		}
	}
}

public partial class GetRepartitionParTypeContratResult
{
	
	private string _TypeContrat;
	
	private System.Nullable<int> _NombreEmployes;
	
	public GetRepartitionParTypeContratResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeContrat", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string TypeContrat
	{
		get
		{
			return this._TypeContrat;
		}
		set
		{
			if ((this._TypeContrat != value))
			{
				this._TypeContrat = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmployes", DbType="Int")]
	public System.Nullable<int> NombreEmployes
	{
		get
		{
			return this._NombreEmployes;
		}
		set
		{
			if ((this._NombreEmployes != value))
			{
				this._NombreEmployes = value;
			}
		}
	}
}

public partial class GetTauxTurnoverResult
{
	
	private System.Nullable<int> _Annee;
	
	private System.Nullable<decimal> _EffectifMoyen;
	
	private System.Nullable<int> _NombreDeparts;
	
	private System.Nullable<int> _NombreEmbauches;
	
	private System.Nullable<decimal> _TauxTurnover;
	
	private System.Nullable<decimal> _TauxRotationGlobale;
	
	public GetTauxTurnoverResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annee", DbType="Int")]
	public System.Nullable<int> Annee
	{
		get
		{
			return this._Annee;
		}
		set
		{
			if ((this._Annee != value))
			{
				this._Annee = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EffectifMoyen", DbType="Decimal(10,2)")]
	public System.Nullable<decimal> EffectifMoyen
	{
		get
		{
			return this._EffectifMoyen;
		}
		set
		{
			if ((this._EffectifMoyen != value))
			{
				this._EffectifMoyen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreDeparts", DbType="Int")]
	public System.Nullable<int> NombreDeparts
	{
		get
		{
			return this._NombreDeparts;
		}
		set
		{
			if ((this._NombreDeparts != value))
			{
				this._NombreDeparts = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreEmbauches", DbType="Int")]
	public System.Nullable<int> NombreEmbauches
	{
		get
		{
			return this._NombreEmbauches;
		}
		set
		{
			if ((this._NombreEmbauches != value))
			{
				this._NombreEmbauches = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TauxTurnover", DbType="Decimal(5,2)")]
	public System.Nullable<decimal> TauxTurnover
	{
		get
		{
			return this._TauxTurnover;
		}
		set
		{
			if ((this._TauxTurnover != value))
			{
				this._TauxTurnover = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TauxRotationGlobale", DbType="Decimal(5,2)")]
	public System.Nullable<decimal> TauxRotationGlobale
	{
		get
		{
			return this._TauxRotationGlobale;
		}
		set
		{
			if ((this._TauxRotationGlobale != value))
			{
				this._TauxRotationGlobale = value;
			}
		}
	}
}

public partial class GetRepartitionHandicapResult
{
	
	private string _Statut;
	
	private System.Nullable<int> _Nombre;
	
	public GetRepartitionHandicapResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statut", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
	public string Statut
	{
		get
		{
			return this._Statut;
		}
		set
		{
			if ((this._Statut != value))
			{
				this._Statut = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="Int")]
	public System.Nullable<int> Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
}

public partial class Permition_GetByIDRoleResult
{
	
	private System.Nullable<bool> _RibbonEffectif;
	
	private System.Nullable<bool> _RibbonParcoursproo;
	
	private System.Nullable<bool> _RibbonCompetences;
	
	private System.Nullable<bool> _RibbonFormation;
	
	private System.Nullable<bool> _RibbonRemuneration;
	
	private System.Nullable<bool> _RibbonSanteSecurites;
	
	private System.Nullable<bool> _RibbonAbsentiesme;
	
	private System.Nullable<bool> _RibbonEmployes;
	
	private System.Nullable<bool> _RibbonSalaire;
	
	private System.Nullable<bool> _RibbonAbsentiesmes;
	
	private System.Nullable<bool> _RibbonFormationmation;
	
	private System.Nullable<bool> _RibbonParcourspro;
	
	private System.Nullable<bool> _RibbonCompetence;
	
	private System.Nullable<bool> _RibbonSanteSecurite;
	
	private System.Nullable<bool> _RibbonDepenseFormation;
	
	private System.Nullable<bool> _RibbonRole;
	
	private System.Nullable<bool> _RibbonPermission;
	
	private System.Nullable<bool> _RibbonRessource;
	
	private System.Nullable<bool> _RibbonControle;
	
	private System.Nullable<bool> _RibbonParametrage;
	
	public Permition_GetByIDRoleResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonEffectif", DbType="Bit")]
	public System.Nullable<bool> RibbonEffectif
	{
		get
		{
			return this._RibbonEffectif;
		}
		set
		{
			if ((this._RibbonEffectif != value))
			{
				this._RibbonEffectif = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonParcoursproo", DbType="Bit")]
	public System.Nullable<bool> RibbonParcoursproo
	{
		get
		{
			return this._RibbonParcoursproo;
		}
		set
		{
			if ((this._RibbonParcoursproo != value))
			{
				this._RibbonParcoursproo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonCompetences", DbType="Bit")]
	public System.Nullable<bool> RibbonCompetences
	{
		get
		{
			return this._RibbonCompetences;
		}
		set
		{
			if ((this._RibbonCompetences != value))
			{
				this._RibbonCompetences = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonFormation", DbType="Bit")]
	public System.Nullable<bool> RibbonFormation
	{
		get
		{
			return this._RibbonFormation;
		}
		set
		{
			if ((this._RibbonFormation != value))
			{
				this._RibbonFormation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonRemuneration", DbType="Bit")]
	public System.Nullable<bool> RibbonRemuneration
	{
		get
		{
			return this._RibbonRemuneration;
		}
		set
		{
			if ((this._RibbonRemuneration != value))
			{
				this._RibbonRemuneration = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonSanteSecurites", DbType="Bit")]
	public System.Nullable<bool> RibbonSanteSecurites
	{
		get
		{
			return this._RibbonSanteSecurites;
		}
		set
		{
			if ((this._RibbonSanteSecurites != value))
			{
				this._RibbonSanteSecurites = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonAbsentiesme", DbType="Bit")]
	public System.Nullable<bool> RibbonAbsentiesme
	{
		get
		{
			return this._RibbonAbsentiesme;
		}
		set
		{
			if ((this._RibbonAbsentiesme != value))
			{
				this._RibbonAbsentiesme = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonEmployes", DbType="Bit")]
	public System.Nullable<bool> RibbonEmployes
	{
		get
		{
			return this._RibbonEmployes;
		}
		set
		{
			if ((this._RibbonEmployes != value))
			{
				this._RibbonEmployes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonSalaire", DbType="Bit")]
	public System.Nullable<bool> RibbonSalaire
	{
		get
		{
			return this._RibbonSalaire;
		}
		set
		{
			if ((this._RibbonSalaire != value))
			{
				this._RibbonSalaire = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonAbsentiesmes", DbType="Bit")]
	public System.Nullable<bool> RibbonAbsentiesmes
	{
		get
		{
			return this._RibbonAbsentiesmes;
		}
		set
		{
			if ((this._RibbonAbsentiesmes != value))
			{
				this._RibbonAbsentiesmes = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonFormationmation", DbType="Bit")]
	public System.Nullable<bool> RibbonFormationmation
	{
		get
		{
			return this._RibbonFormationmation;
		}
		set
		{
			if ((this._RibbonFormationmation != value))
			{
				this._RibbonFormationmation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonParcourspro", DbType="Bit")]
	public System.Nullable<bool> RibbonParcourspro
	{
		get
		{
			return this._RibbonParcourspro;
		}
		set
		{
			if ((this._RibbonParcourspro != value))
			{
				this._RibbonParcourspro = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonCompetence", DbType="Bit")]
	public System.Nullable<bool> RibbonCompetence
	{
		get
		{
			return this._RibbonCompetence;
		}
		set
		{
			if ((this._RibbonCompetence != value))
			{
				this._RibbonCompetence = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonSanteSecurite", DbType="Bit")]
	public System.Nullable<bool> RibbonSanteSecurite
	{
		get
		{
			return this._RibbonSanteSecurite;
		}
		set
		{
			if ((this._RibbonSanteSecurite != value))
			{
				this._RibbonSanteSecurite = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonDepenseFormation", DbType="Bit")]
	public System.Nullable<bool> RibbonDepenseFormation
	{
		get
		{
			return this._RibbonDepenseFormation;
		}
		set
		{
			if ((this._RibbonDepenseFormation != value))
			{
				this._RibbonDepenseFormation = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonRole", DbType="Bit")]
	public System.Nullable<bool> RibbonRole
	{
		get
		{
			return this._RibbonRole;
		}
		set
		{
			if ((this._RibbonRole != value))
			{
				this._RibbonRole = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonPermission", DbType="Bit")]
	public System.Nullable<bool> RibbonPermission
	{
		get
		{
			return this._RibbonPermission;
		}
		set
		{
			if ((this._RibbonPermission != value))
			{
				this._RibbonPermission = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonRessource", DbType="Bit")]
	public System.Nullable<bool> RibbonRessource
	{
		get
		{
			return this._RibbonRessource;
		}
		set
		{
			if ((this._RibbonRessource != value))
			{
				this._RibbonRessource = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonControle", DbType="Bit")]
	public System.Nullable<bool> RibbonControle
	{
		get
		{
			return this._RibbonControle;
		}
		set
		{
			if ((this._RibbonControle != value))
			{
				this._RibbonControle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RibbonParametrage", DbType="Bit")]
	public System.Nullable<bool> RibbonParametrage
	{
		get
		{
			return this._RibbonParametrage;
		}
		set
		{
			if ((this._RibbonParametrage != value))
			{
				this._RibbonParametrage = value;
			}
		}
	}
}

public partial class CountAgeMoyResult
{
	
	private System.Nullable<int> _AgeH;
	
	private System.Nullable<int> _AgeF;
	
	private System.Nullable<int> _AgeMoyen;
	
	public CountAgeMoyResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeH", DbType="Int")]
	public System.Nullable<int> AgeH
	{
		get
		{
			return this._AgeH;
		}
		set
		{
			if ((this._AgeH != value))
			{
				this._AgeH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeF", DbType="Int")]
	public System.Nullable<int> AgeF
	{
		get
		{
			return this._AgeF;
		}
		set
		{
			if ((this._AgeF != value))
			{
				this._AgeF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeMoyen", DbType="Int")]
	public System.Nullable<int> AgeMoyen
	{
		get
		{
			return this._AgeMoyen;
		}
		set
		{
			if ((this._AgeMoyen != value))
			{
				this._AgeMoyen = value;
			}
		}
	}
}

public partial class CountAnciennteResult
{
	
	private System.Nullable<int> _AnciennteH;
	
	private System.Nullable<int> _AnciennteF;
	
	private System.Nullable<int> _AnciennteMoyen;
	
	public CountAnciennteResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnciennteH", DbType="Int")]
	public System.Nullable<int> AnciennteH
	{
		get
		{
			return this._AnciennteH;
		}
		set
		{
			if ((this._AnciennteH != value))
			{
				this._AnciennteH = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnciennteF", DbType="Int")]
	public System.Nullable<int> AnciennteF
	{
		get
		{
			return this._AnciennteF;
		}
		set
		{
			if ((this._AnciennteF != value))
			{
				this._AnciennteF = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnciennteMoyen", DbType="Int")]
	public System.Nullable<int> AnciennteMoyen
	{
		get
		{
			return this._AnciennteMoyen;
		}
		set
		{
			if ((this._AnciennteMoyen != value))
			{
				this._AnciennteMoyen = value;
			}
		}
	}
}

public partial class Afficher_Salaire_MinResult
{
	
	private string _Sexe;
	
	private System.Nullable<double> _Salaire_Minimum;
	
	public Afficher_Salaire_MinResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="NVarChar(MAX)")]
	public string Sexe
	{
		get
		{
			return this._Sexe;
		}
		set
		{
			if ((this._Sexe != value))
			{
				this._Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salaire_Minimum", DbType="Float")]
	public System.Nullable<double> Salaire_Minimum
	{
		get
		{
			return this._Salaire_Minimum;
		}
		set
		{
			if ((this._Salaire_Minimum != value))
			{
				this._Salaire_Minimum = value;
			}
		}
	}
}

public partial class Afficher_Salaire_MaxResult
{
	
	private string _Sexe;
	
	private System.Nullable<double> _Salaire_Max;
	
	public Afficher_Salaire_MaxResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="NVarChar(MAX)")]
	public string Sexe
	{
		get
		{
			return this._Sexe;
		}
		set
		{
			if ((this._Sexe != value))
			{
				this._Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salaire_Max", DbType="Float")]
	public System.Nullable<double> Salaire_Max
	{
		get
		{
			return this._Salaire_Max;
		}
		set
		{
			if ((this._Salaire_Max != value))
			{
				this._Salaire_Max = value;
			}
		}
	}
}

public partial class Afficher_Abs_MaxResult
{
	
	private System.Nullable<int> _ID_Sexe;
	
	private string _Sexe;
	
	private System.Nullable<int> _Max_Jours_Absence;
	
	public Afficher_Abs_MaxResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sexe", DbType="Int")]
	public System.Nullable<int> ID_Sexe
	{
		get
		{
			return this._ID_Sexe;
		}
		set
		{
			if ((this._ID_Sexe != value))
			{
				this._ID_Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
	public string Sexe
	{
		get
		{
			return this._Sexe;
		}
		set
		{
			if ((this._Sexe != value))
			{
				this._Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Max_Jours_Absence", DbType="Int")]
	public System.Nullable<int> Max_Jours_Absence
	{
		get
		{
			return this._Max_Jours_Absence;
		}
		set
		{
			if ((this._Max_Jours_Absence != value))
			{
				this._Max_Jours_Absence = value;
			}
		}
	}
}

public partial class Afficher_Abs_MoyenResult
{
	
	private System.Nullable<int> _ID_Sexe;
	
	private string _Sexe;
	
	private System.Nullable<int> _Moyenne_Jours_Absence;
	
	public Afficher_Abs_MoyenResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Sexe", DbType="Int")]
	public System.Nullable<int> ID_Sexe
	{
		get
		{
			return this._ID_Sexe;
		}
		set
		{
			if ((this._ID_Sexe != value))
			{
				this._ID_Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
	public string Sexe
	{
		get
		{
			return this._Sexe;
		}
		set
		{
			if ((this._Sexe != value))
			{
				this._Sexe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Moyenne_Jours_Absence", DbType="Int")]
	public System.Nullable<int> Moyenne_Jours_Absence
	{
		get
		{
			return this._Moyenne_Jours_Absence;
		}
		set
		{
			if ((this._Moyenne_Jours_Absence != value))
			{
				this._Moyenne_Jours_Absence = value;
			}
		}
	}
}
#pragma warning restore 1591
